local F = require("dashboard/format_es")

describe("format_es", function()
    it("dateTitle", function()
        assert.equals("Miércoles 23 de septiembre", F.dateTitle("2026-09-23", 3))
        assert.equals("Lunes 1 de enero", F.dateTitle("2026-01-01", 1))
        assert.equals("Domingo 31 de diciembre", F.dateTitle("2026-12-31", 7))
    end)

    it("nombres de día y mes, con valores fuera de rango", function()
        assert.equals("Sábado", F.weekdayName(6))
        assert.equals("marzo", F.monthName(3))
        assert.equals("", F.weekdayName(9))
        assert.equals("", F.dayMonth("basura"))
    end)

    it("ageLabel", function()
        assert.equals("hace unos segundos", F.ageLabel(20))
        assert.equals("hace 1 min", F.ageLabel(60))
        assert.equals("hace 5 min", F.ageLabel(5 * 60 + 59))
        assert.equals("hace 1 h", F.ageLabel(3600))
        assert.equals("hace 2 h", F.ageLabel(2 * 3600 + 1800))
        assert.equals("hace 1 día", F.ageLabel(86400 + 5000))
        assert.equals("hace 3 días", F.ageLabel(3 * 86400))
        assert.equals("hace unos segundos", F.ageLabel(-5))
    end)

    it("timeRange", function()
        assert.equals("Todo el día", F.timeRange({ all_day = true }))
        assert.equals("14:00–14:15", F.timeRange({ all_day = false, start = "14:00", ["end"] = "14:15" }))
        assert.equals("15:00", F.timeRange({ all_day = false, start = "15:00", ["end"] = "15:00" }))
        assert.equals("15:00", F.timeRange({ all_day = false, start = "15:00" }))
    end)

    it("more y updatedAt", function()
        assert.equals("+2 más", F.more(2))
        assert.equals("13:40", F.updatedAt("2026-09-23T13:40:00-03:00"))
        assert.is_nil(F.updatedAt("basura"))
    end)
end)
